In [1]:
import gensim
import nltk
import gensim.corpora as corpora
from gensim.models import LdaModel
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.stem.wordnet import WordNetLemmatizer
import spacy 
import re

In [2]:
# # Download necessary NLTK resources
# nltk.download('puntk')
# nltk.download('wordnet')
# nltk.download('omw-1.4')
# nltk.download('stopwords')

[nltk_data] Error loading puntk: Package 'puntk' not found in index
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Shrawani\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Shrawani\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Shrawani\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
text = [
    "Artificial intelligence is transforming the world. Many companies are investing in AI research and development.",
    "The new iPhone was released last week, and it features a better camera, improved battery life, and faster processing.",
    "Climate change is one of the most pressing issues of our time. Governments worldwide are working to reduce carbon emissions.",
    "The stock market saw significant gains today, with technology stocks leading the way.",
    "Advances in medical technology have led to better treatments for chronic diseases, improving patient outcomes."
]

In [3]:
# Intialize spacy 'en' model, keeping only tagger component need for lemmatization
nlp = spacy.load('en_core_web_md')

# Tokenization, removing stopword, non-alphabetic characters and lemmatization
stop_words = set(stopwords.words('english'))
lemmatizater = WordNetLemmatizer()

def preprocess(text):
    text = text.lower() # convert to lower
    tokens = word_tokenize(text) # tokenize
    tokens = [lemmatizater.lemmatize(word) for word in tokens if word not in stop_words] #lemmatize and remove 
    return tokens

processed_docs = [preprocess(doc) for doc in text]

In [4]:
# Create Dictonary 
id2word = corpora.Dictionary(processed_docs)

corpus = [id2word.doc2bow(text) for text in processed_docs]

# view the corpus
print(corpus)

[[(0, 2), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1)], [(0, 1), (11, 3), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1)], [(0, 2), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1), (36, 1)], [(0, 1), (11, 1), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1), (42, 2), (43, 1), (44, 1), (45, 1)], [(0, 1), (11, 1), (13, 1), (43, 1), (46, 1), (47, 1), (48, 1), (49, 1), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1)]]

In [6]:
# build LDA model
lda_model = LdaModel(corpus=corpus,
                     id2word=id2word,
                     num_topics=3,
                     random_state=42,
                     update_every=1,
                     chunksize=10,
                     passes=10,
                     alpha='auto')

# Print the keyword in 2 topics
topics = lda_model.print_topics()
for topic in topics:
    print(topic)

(0, '0.066*"." + 0.066*"," + 0.030*"stock" + 0.030*"technology" + 0.030*"better" + 0.018*"life" + 0.018*"released" + 0.018*"battery" + 0.018*"week" + 0.018*"saw"')
(1, '0.063*"." + 0.038*"transforming" + 0.038*"world" + 0.038*"company" + 0.038*"research" + 0.038*"investing" + 0.038*"artificial" + 0.038*"ai" + 0.038*"many" + 0.038*"development"')

In [7]:
#!pip install pyLDAvis

In [9]:
import pyLDAvis
import pyLDAvis.gensim_models as gensimvis

#prepare the visualization
lda_vis = gensimvis.prepare(lda_model,corpus,id2word)
pyLDAvis.display(lda_vis)

In [9]:
# Install Required Libraries
#!pip install gensim nltk

# Import Necessary Libraries
import gensim
from gensim import corpora
from gensim.models import LdaModel
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

# # Download required NLTK datasets for tokenization and stopwords
# nltk.download('punkt')
# nltk.download('stopwords')

# Create a Corpus of 10 Documents
# This is a small set of text documents that we want to analyze for topic modeling
documents = [
 "Apple is looking at buying U.K. startup for $1 billion",
 "Apple buys U.K. startup for $1 billion",
 "San Francisco considers banning sidewalk delivery robots",
 "London is a very big city in the United Kingdom",
 "Football is a popular sport in Europe",
 "The price of oil has increased by 10% last year",
 "Technology companies are growing fast",
 "The global economy is expected to grow this year",
 "Apple is a technology company with a focus on innovation",
 "The United Kingdom is known for its rich history and culture"
]

# Preprocess the Text
# This function tokenizes the text, converts it to lowercase, and removes stopwords
stop_words = set(stopwords.words('english'))

def preprocess(doc):
 # Tokenize the document into words
 tokens = word_tokenize(doc.lower())
 # Filter out non-alphabetic words and stopwords
 tokens = [word for word in tokens if word.isalpha() and word not in stop_words]
 return tokens

# Apply preprocessing to all documents in the corpus
processed_docs = [preprocess(doc) for doc in documents]
print(processed_docs)
print("---------------"*5)
# Create a Dictionary and Corpus
# Dictionary maps each word to a unique ID
dictionary = corpora.Dictionary(processed_docs)
print(dictionary)
print("---------------"*5)

# Corpus is a list of Bag-of-Words (BoW) representations of the documents
corpus = [dictionary.doc2bow(doc) for doc in processed_docs]
print(corpus)
print("---------------"*5)

# Perform LDA Topic Modeling
# LDA (Latent Dirichlet Allocation) is used to discover topics within the corpus
num_topics = 3 # Number of topics you want to extract (can be adjusted)
lda_model = LdaModel(corpus, num_topics=num_topics, id2word=dictionary, passes=15)

# Print the Topics
# This prints the top words associated with each topic
topics = lda_model.print_topics(num_words=4)
for idx, topic in topics:
 print(f"Topic {idx}: {topic}")

# Assign Each Document to Topics
# For each document, we print the distribution of topics it belongs to
for i, doc in enumerate(corpus):
 topics_in_doc = lda_model.get_document_topics(doc)
 print(f"Document {i+1} is associated with topics: {topics_in_doc}")

[['apple', 'looking', 'buying', 'startup', 'billion'], ['apple', 'buys', 'startup', 'billion'], ['san', 'francisco', 'considers', 'banning', 'sidewalk', 'delivery', 'robots'], ['london', 'big', 'city', 'united', 'kingdom'], ['football', 'popular', 'sport', 'europe'], ['price', 'oil', 'increased', 'last', 'year'], ['technology', 'companies', 'growing', 'fast'], ['global', 'economy', 'expected', 'grow', 'year'], ['apple', 'technology', 'company', 'focus', 'innovation'], ['united', 'kingdom', 'known', 'rich', 'history', 'culture']]
---------------------------------------------------------------------------
Dictionary<42 unique tokens: ['apple', 'billion', 'buying', 'looking', 'startup']...>
---------------------------------------------------------------------------
[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)], [(0, 1), (1, 1), (4, 1), (5, 1)], [(6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1)], [(13, 1), (14, 1), (15, 1), (16, 1), (17, 1)], [(18, 1), (19, 1), (20, 1), (21, 1)], [(22, 1), (23, 1), (24, 1), (25, 1), (26, 1)], [(27, 1), (28, 1), (29, 1), (30, 1)], [(26, 1), (31, 1), (32, 1), (33, 1), (34, 1)], [(0, 1), (30, 1), (35, 1), (36, 1), (37, 1)], [(15, 1), (17, 1), (38, 1), (39, 1), (40, 1), (41, 1)]]
---------------------------------------------------------------------------
Topic 0: 0.103*"apple" + 0.101*"startup" + 0.101*"billion" + 0.058*"buying"
Topic 1: 0.071*"technology" + 0.040*"year" + 0.040*"kingdom" + 0.040*"united"
Topic 2: 0.037*"united" + 0.037*"kingdom" + 0.037*"history" + 0.037*"culture"
Document 1 is associated with topics: [(0, 0.8880768), (1, 0.056202956), (2, 0.055720232)]
Document 2 is associated with topics: [(0, 0.86558634), (1, 0.06757121), (2, 0.06684251)]
Document 3 is associated with topics: [(0, 0.042132422), (1, 0.041981086), (2, 0.9158865)]
Document 4 is associated with topics: [(0, 0.056118168), (1, 0.8846832), (2, 0.059198644)]
Document 5 is associated with topics: [(0, 0.067418575), (1, 0.06717946), (2, 0.865402)]
Document 6 is associated with topics: [(0, 0.056172546), (1, 0.057809256), (2, 0.8860182)]
Document 7 is associated with topics: [(0, 0.067256816), (1, 0.8657075), (2, 0.06703568)]
Document 8 is associated with topics: [(0, 0.05611714), (1, 0.8865049), (2, 0.05737795)]
Document 9 is associated with topics: [(0, 0.06331954), (1, 0.8808082), (2, 0.055872303)]
Document 10 is associated with topics: [(0, 0.048144534), (1, 0.050811738), (2, 0.9010437)]

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv(r"C:\Users\Shrawani\Downloads\BBC News Train.csv")  # Adjust the file path
print(df.head())

   ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [3]:
df['Text'][0]

'worldcom ex-boss launches defence lawyers defending former worldcom chief bernie ebbers against a battery of fraud charges have called a company whistleblower as their first witness.  cynthia cooper  worldcom s ex-head of internal accounting  alerted directors to irregular accounting practices at the us telecoms giant in 2002. her warnings led to the collapse of the firm following the discovery of an $11bn (£5.7bn) accounting fraud. mr ebbers has pleaded not guilty to charges of fraud and conspiracy.  prosecution lawyers have argued that mr ebbers orchestrated a series of accounting tricks at worldcom  ordering employees to hide expenses and inflate revenues to meet wall street earnings estimates. but ms cooper  who now runs her own consulting business  told a jury in new york on wednesday that external auditors arthur andersen had approved worldcom s accounting in early 2001 and 2002. she said andersen had given a  green light  to the procedures and practices used by worldcom. mr ebber s lawyers have said he was unaware of the fraud  arguing that auditors did not alert him to any problems.  ms cooper also said that during shareholder meetings mr ebbers often passed over technical questions to the company s finance chief  giving only  brief  answers himself. the prosecution s star witness  former worldcom financial chief scott sullivan  has said that mr ebbers ordered accounting adjustments at the firm  telling him to  hit our books . however  ms cooper said mr sullivan had not mentioned  anything uncomfortable  about worldcom s accounting during a 2001 audit committee meeting. mr ebbers could face a jail sentence of 85 years if convicted of all the charges he is facing. worldcom emerged from bankruptcy protection in 2004  and is now known as mci. last week  mci agreed to a buyout by verizon communications in a deal valued at $6.75bn.'

In [2]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk.download('stopwords')
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = text.lower()  # Convert to lowercase
    text = text.split()  # Tokenize
    text = [lemmatizer.lemmatize(word) for word in text if word not in stopwords.words('english')]
    return ' '.join(text)

df['cleaned_text'] = df['Text'].apply(clean_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Shrawani\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Shrawani\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [4]:
df

,ArticleId,Text,Category,cleaned_text
0,1833,worldcom ex-boss launches defence lawyers defe...,business,worldcom exboss launch defence lawyer defendin...
1,154,german business confidence slides german busin...,business,german business confidence slide german busine...
2,1101,bbc poll indicates economic gloom citizens in ...,business,bbc poll indicates economic gloom citizen majo...
3,1976,lifestyle governs mobile choice faster bett...,tech,lifestyle governs mobile choice faster better ...
4,917,enron bosses in $168m payout eighteen former e...,business,enron boss payout eighteen former enron direct...
...,...,...,...,...
1485,857,double eviction from big brother model caprice...,entertainment,double eviction big brother model caprice holb...
1486,325,dj double act revamp chart show dj duo jk and ...,entertainment,dj double act revamp chart show dj duo jk joel...
1487,1590,weak dollar hits reuters revenues at media gro...,business,weak dollar hit reuters revenue medium group r...
1488,1587,apple ipod family expands market apple has exp...,tech,apple ipod family expands market apple expande...
1489,538,santy worm makes unwelcome visit thousands of ...,tech,santy worm make unwelcome visit thousand websi...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)
tfidf_matrix = tfidf.fit_transform(df['cleaned_text'])

In [6]:
from sklearn.decomposition import LatentDirichletAllocation

# Set the number of topics
n_topics = 5  # Adjust based on experimentation
lda = LatentDirichletAllocation(n_components=n_topics, random_state=42)
lda.fit(tfidf_matrix)

LatentDirichletAllocation(n_components=5, random_state=42)

In [7]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print(f"Topic {topic_idx}:")
        print(" ".join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))

tfidf_feature_names = tfidf.get_feature_names_out()
display_topics(lda, tfidf_feature_names, 10)  # Display top 10 words per topic

Topic 0:
said mr would year people new government bn also firm
Topic 1:
band album chart singer song music star single film festival
Topic 2:
fiat conte cairn mitsubishi bmw slowdown vodafone crude firefox balco
Topic 3:
film best award game win england champion match cup first
Topic 4:
console nintendo xbox gamers psp dvd highdefinition halo commodore sony

In [8]:
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary
from gensim.models.ldamodel import LdaModel

# Convert the dataset into a Gensim-friendly format
tokenized_text = [text.split() for text in df['cleaned_text']]
dictionary = Dictionary(tokenized_text)
corpus = [dictionary.doc2bow(text) for text in tokenized_text]

# Train LDA with Gensim
lda_model = LdaModel(corpus=corpus, num_topics=n_topics, id2word=dictionary, passes=15)

# Compute coherence score
coherence_model = CoherenceModel(model=lda_model, texts=tokenized_text, dictionary=dictionary, coherence='c_v')
coherence_score = coherence_model.get_coherence()
print(f"Coherence Score: {coherence_score}")

Coherence Score: 0.45869991833884594

In [11]:
import pyLDAvis.gensim_models as gensimvis
import pyLDAvis

pyLDAvis.enable_notebook()  # Enables inline visualization
vis = gensimvis.prepare(lda_model, corpus, dictionary)
vis

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0      0.025943  0.018379       1        1  26.969018
2      0.068337  0.122767       2        1  21.943024
4     -0.187555  0.025533       3        1  19.681750
3      0.087521 -0.038136       4        1  18.464327
1      0.005755 -0.128543       5        1  12.941881, topic_info=         Term        Freq        Total Category  logprob  loglift
460      film  710.000000   710.000000  Default  30.0000  30.0000
1353     best  542.000000   542.000000  Default  29.0000  29.0000
507    mobile  432.000000   432.000000  Default  28.0000  28.0000
704      game  886.000000   886.000000  Default  27.0000  27.0000
868     award  338.000000   338.000000  Default  26.0000  26.0000
...       ...         ...          ...      ...      ...      ...
67        hit   85.856803   264.853407   Topic5  -6.1700   0.9182
262     would   97.337192  1611.092325   Topic5  -6.0445  -0.7618
29    company   89.773722   643.707827   Topic5  -6.1254   0.0747
695       day   86.940037   419.416198   Topic5  -6.1575   0.4711
648   million   86.454333   407.979959   Topic5  -6.1631   0.4931

[425 rows x 6 columns], token_table=      Topic      Freq             Term
term
7384      3  0.970036               ac
7824      1  0.016222          academy
7824      2  0.016222          academy
7824      3  0.032444          academy
7824      5  0.924653          academy
...     ...       ...              ...
127       5  0.187695             year
2220      5  0.976158          yugansk
2221      5  0.967240  yuganskneftegas
2222      4  0.130539            yukos
2222      5  0.867151            yukos

[1077 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 3, 5, 4, 2])

In [12]:
def categorize_article(text):
    bow = dictionary.doc2bow(text.split())
    topic_distribution = lda_model.get_document_topics(bow)
    return max(topic_distribution, key=lambda x: x[1])[0]  # Return topic with highest weight

df['predicted_category'] = df['cleaned_text'].apply(categorize_article)

In [13]:
df

,ArticleId,Text,Category,cleaned_text,predicted_category
0,1833,worldcom ex-boss launches defence lawyers defe...,business,worldcom exboss launch defence lawyer defendin...,3
1,154,german business confidence slides german busin...,business,german business confidence slide german busine...,3
2,1101,bbc poll indicates economic gloom citizens in ...,business,bbc poll indicates economic gloom citizen majo...,3
3,1976,lifestyle governs mobile choice faster bett...,tech,lifestyle governs mobile choice faster better ...,2
4,917,enron bosses in $168m payout eighteen former e...,business,enron boss payout eighteen former enron direct...,3
...,...,...,...,...,...
1485,857,double eviction from big brother model caprice...,entertainment,double eviction big brother model caprice holb...,0
1486,325,dj double act revamp chart show dj duo jk and ...,entertainment,dj double act revamp chart show dj duo jk joel...,0
1487,1590,weak dollar hits reuters revenues at media gro...,business,weak dollar hit reuters revenue medium group r...,3
1488,1587,apple ipod family expands market apple has exp...,tech,apple ipod family expands market apple expande...,2
1489,538,santy worm makes unwelcome visit thousands of ...,tech,santy worm make unwelcome visit thousand websi...,2

In [40]:
import nltk 
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

sent = """worldcom ex-boss launches defence lawyers defending former worldcom chief bernie ebbers against a battery of 
fraud charges have called a company whistleblower as their first witness.  cynthia cooper  worldcom s ex-head of internal accounting  
alerted directors to irregular accounting practices at the us telecoms giant in 2002. her warnings led to the collapse of the firm 
following the discovery of an $11bn (£5.7bn) accounting fraud. mr ebbers has pleaded not guilty to charges of fraud and conspiracy.  
prosecution lawyers have argued that mr ebbers orchestrated a series of accounting tricks at worldcom  ordering employees to hide expenses and 
inflate revenues to meet wall street earnings estimates. but ms cooper  who now runs her own consulting business  told a jury in 
new york on wednesday that external auditors arthur andersen had approved worldcom s accounting in early 2001 and 2002. 
she said andersen had given a  green light  to the procedures and practices used by worldcom. mr ebber s lawyers have said he was 
unaware of the fraud  arguing that auditors did not alert him to any problems.  ms cooper also said that during shareholder meetings 
mr ebbers often passed over technical questions to the company s finance chief  giving only  brief  answers himself. the prosecution s 
star witness  former worldcom financial chief scott sullivan  has said that mr ebbers ordered accounting adjustments at the firm  
telling him to  hit our books . however  ms cooper said mr sullivan had not mentioned  anything uncomfortable  about worldcom s accounting 
during a 2001 audit committee meeting. mr ebbers could face a jail sentence of 85 years if convicted of all the charges he is facing.
worldcom emerged from bankruptcy protection in 2004  and is now known as mci. last week  mci agreed to a buyout by verizon communications 
in a deal valued at $6.75bn."""

In [17]:
sent1 = sent_tokenize(sent)

In [18]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [36]:
sents = RecursiveCharacterTextSplitter(chunk_size = 50, chunk_overlap=30, length_function=len)

In [37]:
# Split the text into chunks
chunks = sents.split_text(sent)

In [38]:
len(chunks)

82

In [39]:
chunks

['worldcom ex-boss launches defence lawyers',
 'launches defence lawyers defending former',
 'lawyers defending former worldcom chief bernie',
 'former worldcom chief bernie ebbers against a',
 'chief bernie ebbers against a battery of',
 'fraud charges have called a company whistleblower',
 'a company whistleblower as their first witness.',
 'as their first witness.  cynthia cooper  worldcom',
 'cynthia cooper  worldcom s ex-head of internal',
 's ex-head of internal accounting',
 'alerted directors to irregular accounting',
 'to irregular accounting practices at the us',
 'practices at the us telecoms giant in 2002. her',
 'telecoms giant in 2002. her warnings led to the',
 '2002. her warnings led to the collapse of the',
 'led to the collapse of the firm',
 'following the discovery of an $11bn (£5.7bn)',
 'of an $11bn (£5.7bn) accounting fraud. mr ebbers',
 'accounting fraud. mr ebbers has pleaded not',
 'mr ebbers has pleaded not guilty to charges of',
 'not guilty to charges of fraud and conspiracy.',
 'prosecution lawyers have argued that mr ebbers',
 'have argued that mr ebbers orchestrated a series',
 'ebbers orchestrated a series of accounting tricks',
 'a series of accounting tricks at worldcom',
 'tricks at worldcom  ordering employees to hide',
 'ordering employees to hide expenses and',
 'inflate revenues to meet wall street earnings',
 'to meet wall street earnings estimates. but ms',
 'earnings estimates. but ms cooper  who now runs',
 'but ms cooper  who now runs her own consulting',
 'now runs her own consulting business  told a jury',
 'business  told a jury in',
 'new york on wednesday that external auditors',
 'that external auditors arthur andersen had',
 'auditors arthur andersen had approved worldcom s',
 'had approved worldcom s accounting in early 2001',
 's accounting in early 2001 and 2002.',
 'she said andersen had given a  green light  to',
 'had given a  green light  to the procedures and',
 'light  to the procedures and practices used by',
 'and practices used by worldcom. mr ebber s',
 'used by worldcom. mr ebber s lawyers have said he',
 'ebber s lawyers have said he was',
 'unaware of the fraud  arguing that auditors did',
 'arguing that auditors did not alert him to any',
 'did not alert him to any problems.  ms cooper',
 'to any problems.  ms cooper also said that during',
 'cooper also said that during shareholder meetings',
 'during shareholder meetings',
 'mr ebbers often passed over technical questions',
 'over technical questions to the company s finance',
 'to the company s finance chief  giving only',
 's finance chief  giving only  brief  answers',
 'giving only  brief  answers himself. the',
 'brief  answers himself. the prosecution s',
 'star witness  former worldcom financial chief',
 'worldcom financial chief scott sullivan  has said',
 'scott sullivan  has said that mr ebbers ordered',
 'said that mr ebbers ordered accounting',
 'mr ebbers ordered accounting adjustments at the',
 'accounting adjustments at the firm',
 'telling him to  hit our books . however  ms',
 'hit our books . however  ms cooper said mr',
 '. however  ms cooper said mr sullivan had not',
 'said mr sullivan had not mentioned  anything',
 'had not mentioned  anything uncomfortable  about',
 'anything uncomfortable  about worldcom s',
 'about worldcom s accounting',
 'during a 2001 audit committee meeting. mr ebbers',
 'committee meeting. mr ebbers could face a jail',
 'mr ebbers could face a jail sentence of 85 years',
 'a jail sentence of 85 years if convicted of all',
 '85 years if convicted of all the charges he is',
 'of all the charges he is facing.',
 'worldcom emerged from bankruptcy protection in',
 'from bankruptcy protection in 2004  and is now',
 'in 2004  and is now known as mci. last week  mci',
 'known as mci. last week  mci agreed to a buyout',
 'week  mci agreed to a buyout by verizon',
 'agreed to a buyout by verizon communications',
 'in a deal valued at $6.75bn.']

In [45]:
from nltk.tokenize import word_tokenize

word_tokenize(sent)

['worldcom',
 'ex-boss',
 'launches',
 'defence',
 'lawyers',
 'defending',
 'former',
 'worldcom',
 'chief',
 'bernie',
 'ebbers',
 'against',
 'a',
 'battery',
 'of',
 'fraud',
 'charges',
 'have',
 'called',
 'a',
 'company',
 'whistleblower',
 'as',
 'their',
 'first',
 'witness',
 '.',
 'cynthia',
 'cooper',
 'worldcom',
 's',
 'ex-head',
 'of',
 'internal',
 'accounting',
 'alerted',
 'directors',
 'to',
 'irregular',
 'accounting',
 'practices',
 'at',
 'the',
 'us',
 'telecoms',
 'giant',
 'in',
 '2002.',
 'her',
 'warnings',
 'led',
 'to',
 'the',
 'collapse',
 'of',
 'the',
 'firm',
 'following',
 'the',
 'discovery',
 'of',
 'an',
 '$',
 '11bn',
 '(',
 '£5.7bn',
 ')',
 'accounting',
 'fraud',
 '.',
 'mr',
 'ebbers',
 'has',
 'pleaded',
 'not',
 'guilty',
 'to',
 'charges',
 'of',
 'fraud',
 'and',
 'conspiracy',
 '.',
 'prosecution',
 'lawyers',
 'have',
 'argued',
 'that',
 'mr',
 'ebbers',
 'orchestrated',
 'a',
 'series',
 'of',
 'accounting',
 'tricks',
 'at',
 'worldcom',
 'ordering',
 'employees',
 'to',
 'hide',
 'expenses',
 'and',
 'inflate',
 'revenues',
 'to',
 'meet',
 'wall',
 'street',
 'earnings',
 'estimates',
 '.',
 'but',
 'ms',
 'cooper',
 'who',
 'now',
 'runs',
 'her',
 'own',
 'consulting',
 'business',
 'told',
 'a',
 'jury',
 'in',
 'new',
 'york',
 'on',
 'wednesday',
 'that',
 'external',
 'auditors',
 'arthur',
 'andersen',
 'had',
 'approved',
 'worldcom',
 's',
 'accounting',
 'in',
 'early',
 '2001',
 'and',
 '2002.',
 'she',
 'said',
 'andersen',
 'had',
 'given',
 'a',
 'green',
 'light',
 'to',
 'the',
 'procedures',
 'and',
 'practices',
 'used',
 'by',
 'worldcom',
 '.',
 'mr',
 'ebber',
 's',
 'lawyers',
 'have',
 'said',
 'he',
 'was',
 'unaware',
 'of',
 'the',
 'fraud',
 'arguing',
 'that',
 'auditors',
 'did',
 'not',
 'alert',
 'him',
 'to',
 'any',
 'problems',
 '.',
 'ms',
 'cooper',
 'also',
 'said',
 'that',
 'during',
 'shareholder',
 'meetings',
 'mr',
 'ebbers',
 'often',
 'passed',
 'over',
 'technical',
 'questions',
 'to',
 'the',
 'company',
 's',
 'finance',
 'chief',
 'giving',
 'only',
 'brief',
 'answers',
 'himself',
 '.',
 'the',
 'prosecution',
 's',
 'star',
 'witness',
 'former',
 'worldcom',
 'financial',
 'chief',
 'scott',
 'sullivan',
 'has',
 'said',
 'that',
 'mr',
 'ebbers',
 'ordered',
 'accounting',
 'adjustments',
 'at',
 'the',
 'firm',
 'telling',
 'him',
 'to',
 'hit',
 'our',
 'books',
 '.',
 'however',
 'ms',
 'cooper',
 'said',
 'mr',
 'sullivan',
 'had',
 'not',
 'mentioned',
 'anything',
 'uncomfortable',
 'about',
 'worldcom',
 's',
 'accounting',
 'during',
 'a',
 '2001',
 'audit',
 'committee',
 'meeting',
 '.',
 'mr',
 'ebbers',
 'could',
 'face',
 'a',
 'jail',
 'sentence',
 'of',
 '85',
 'years',
 'if',
 'convicted',
 'of',
 'all',
 'the',
 'charges',
 'he',
 'is',
 'facing',
 '.',
 'worldcom',
 'emerged',
 'from',
 'bankruptcy',
 'protection',
 'in',
 '2004',
 'and',
 'is',
 'now',
 'known',
 'as',
 'mci',
 '.',
 'last',
 'week',
 'mci',
 'agreed',
 'to',
 'a',
 'buyout',
 'by',
 'verizon',
 'communications',
 'in',
 'a',
 'deal',
 'valued',
 'at',
 '$',
 '6.75bn',
 '.']

In [44]:
from nltk.tokenize import WhitespaceTokenizer

WhitespaceTokenizer().tokenize(sent)

['worldcom',
 'ex-boss',
 'launches',
 'defence',
 'lawyers',
 'defending',
 'former',
 'worldcom',
 'chief',
 'bernie',
 'ebbers',
 'against',
 'a',
 'battery',
 'of',
 'fraud',
 'charges',
 'have',
 'called',
 'a',
 'company',
 'whistleblower',
 'as',
 'their',
 'first',
 'witness.',
 'cynthia',
 'cooper',
 'worldcom',
 's',
 'ex-head',
 'of',
 'internal',
 'accounting',
 'alerted',
 'directors',
 'to',
 'irregular',
 'accounting',
 'practices',
 'at',
 'the',
 'us',
 'telecoms',
 'giant',
 'in',
 '2002.',
 'her',
 'warnings',
 'led',
 'to',
 'the',
 'collapse',
 'of',
 'the',
 'firm',
 'following',
 'the',
 'discovery',
 'of',
 'an',
 '$11bn',
 '(£5.7bn)',
 'accounting',
 'fraud.',
 'mr',
 'ebbers',
 'has',
 'pleaded',
 'not',
 'guilty',
 'to',
 'charges',
 'of',
 'fraud',
 'and',
 'conspiracy.',
 'prosecution',
 'lawyers',
 'have',
 'argued',
 'that',
 'mr',
 'ebbers',
 'orchestrated',
 'a',
 'series',
 'of',
 'accounting',
 'tricks',
 'at',
 'worldcom',
 'ordering',
 'employees',
 'to',
 'hide',
 'expenses',
 'and',
 'inflate',
 'revenues',
 'to',
 'meet',
 'wall',
 'street',
 'earnings',
 'estimates.',
 'but',
 'ms',
 'cooper',
 'who',
 'now',
 'runs',
 'her',
 'own',
 'consulting',
 'business',
 'told',
 'a',
 'jury',
 'in',
 'new',
 'york',
 'on',
 'wednesday',
 'that',
 'external',
 'auditors',
 'arthur',
 'andersen',
 'had',
 'approved',
 'worldcom',
 's',
 'accounting',
 'in',
 'early',
 '2001',
 'and',
 '2002.',
 'she',
 'said',
 'andersen',
 'had',
 'given',
 'a',
 'green',
 'light',
 'to',
 'the',
 'procedures',
 'and',
 'practices',
 'used',
 'by',
 'worldcom.',
 'mr',
 'ebber',
 's',
 'lawyers',
 'have',
 'said',
 'he',
 'was',
 'unaware',
 'of',
 'the',
 'fraud',
 'arguing',
 'that',
 'auditors',
 'did',
 'not',
 'alert',
 'him',
 'to',
 'any',
 'problems.',
 'ms',
 'cooper',
 'also',
 'said',
 'that',
 'during',
 'shareholder',
 'meetings',
 'mr',
 'ebbers',
 'often',
 'passed',
 'over',
 'technical',
 'questions',
 'to',
 'the',
 'company',
 's',
 'finance',
 'chief',
 'giving',
 'only',
 'brief',
 'answers',
 'himself.',
 'the',
 'prosecution',
 's',
 'star',
 'witness',
 'former',
 'worldcom',
 'financial',
 'chief',
 'scott',
 'sullivan',
 'has',
 'said',
 'that',
 'mr',
 'ebbers',
 'ordered',
 'accounting',
 'adjustments',
 'at',
 'the',
 'firm',
 'telling',
 'him',
 'to',
 'hit',
 'our',
 'books',
 '.',
 'however',
 'ms',
 'cooper',
 'said',
 'mr',
 'sullivan',
 'had',
 'not',
 'mentioned',
 'anything',
 'uncomfortable',
 'about',
 'worldcom',
 's',
 'accounting',
 'during',
 'a',
 '2001',
 'audit',
 'committee',
 'meeting.',
 'mr',
 'ebbers',
 'could',
 'face',
 'a',
 'jail',
 'sentence',
 'of',
 '85',
 'years',
 'if',
 'convicted',
 'of',
 'all',
 'the',
 'charges',
 'he',
 'is',
 'facing.',
 'worldcom',
 'emerged',
 'from',
 'bankruptcy',
 'protection',
 'in',
 '2004',
 'and',
 'is',
 'now',
 'known',
 'as',
 'mci.',
 'last',
 'week',
 'mci',
 'agreed',
 'to',
 'a',
 'buyout',
 'by',
 'verizon',
 'communications',
 'in',
 'a',
 'deal',
 'valued',
 'at',
 '$6.75bn.']